---
- name: Practice with variable manipulation
  hosts: localhost
  gather_facts: False

  vars_files:
    - ~/mycode/vars/storagevars.yml

  tasks:

    - name: Loop across the list mapped to storage_work.ipv4
      debug:
        var: item.name
      loop: "{{ storage_work.ipv4 }}"

